name: Renouveler Contrats

on:
  schedule:
    - cron: '0 0 * * *'  # Tous les jours à minuit
  workflow_dispatch:       # Permet de lancer manuellement aussi

jobs:
  renouveler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: |
          cd scripts
          npm install

      - name: Lancer le script
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          cd scripts
          node renouveler-contrats.js